spring.application.name=krisefikser
security.jwt.secret-key=testsecrettestsecrettestsecret

spring.datasource.url=jdbc:h2:mem:testdb ;TODO use different db config
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect